### ISSUE TITLE
Allow running of additional PhantomJS code before pa11y runs

### ISSUE THREAD

**Issue by rowanmanning** [nature/pa11y#98] opened 2015-10-08 10:10 UTC
Currently there are some issues around login forms and pages that rely on a lot of JavaScript to render. We have the `wait` option for the latter, but it's not ideal.

Proposing adding the ability to run additional custom PhantomJS code before pa11y to prepare the page for testing. Not sure how this would look yet, but I'll throw together some ideas when I have time.

**Comment by GlynnPhillips** [comment] 2015-12-21 09:48
I started looking at this but then realised my solution was not the best for all cases so it might be helpful to figure out what the user cases we are trying to cover. A couple I can think of:

* Allowing for UI changes e.g. clicking on an element to open a hidden section
* Adding data and submitting form elements e.g. Log in
* Allowing for ajax requests to be made to update content

Some of the problems I was hitting when thinking about these was how to pass back a message to pa11y that the script had finished and the testing could continue. Phantom has a couple options which could work like `onCallback` and `onConsoleMessage` but I couldn't make my mind up as to which would be right in this case. 

It also might be worth defining if these interactions should/would allow for page refreshes or location changes so this might effect the way in which the message is passed back that the script has finished, or might not be possible in cases.

**Comment by JeffHall** [comment] 2015-12-28 20:36
I've just started experimenting with pa11y, and I'm very impressed by what I've seen so far!

So the obvious caveat is that I'm a newbie, but in thinking about this issue and the user cases that @GlynnPhillips mentions above, these are the ones that jump out at me:

* Allowing for UI changes e.g. clicking on an element to open a hidden section
* Allowing for ajax requests to be made to update content

The AngularJS app that I'm working with has several *ngClick* directives that change the state of the page display (essentially show/hide behaviors), so using PhantomJS to navigate to the expected page "state" would be ideal before the pa11y verification itself is run.

Now my challenge is to learn enough JavaScript and Node so that I can actually contribute to this great project!

**Comment by rowanmanning** [comment] 2016-01-27 09:14
After a bit of thought I think that the simplest way to do this would be to give the end user a place to hook into PhantomJS directly. We could just stick an [extra function in here](https://github.com/nature/pa11y/blob/master/lib/pa11y.js#L123) which just runs the user code if there is some, then they can do whatever the hell they want and we cater for all the above use-cases (and more that we can't think of).

API-wise it'd be nice to do something like:

### Command Line

```sh
pa11y --extras ./my-function.js nature.com
```

Where `./my-function.js` is a Node.js module that exports a single function (see below for the expected args for that function).

### JavaScript

```js
pa11y({
    extras: function(page, done) {
        // do stuff here
    }
});
```

Where `page` is the PhantomJS page you're working with, and `done` is a callback to trigger when you've finished.

Not convinced on `extras` as a name, but you get the picture. @GlynnPhillips, @JeffHall, thoughts on this?

**Comment by GlynnPhillips** [comment] 2016-01-27 09:40
That sounds good to me and solves the issues I was having with how to let pa11y know when the script is finished. 

I had previously played with adding the function at pretty much the exact point you referenced inside `lib/pally.js`. Here is an example of what I had.


```javascript
function(next) {
	if (options.injectJs) {
		options.log.debug('Injecting supplied JavaScript');
		page.injectJs(options.injectJs, function(error, injected) {
			if (error) {
				return next(error);
			}
			if (!injected) {
				return next(new Error('Pa11y was unable to inject supplied scripts into the page'));
			}

		});

		// Here I was playing with different ways of knowing when the script had finished such as onCallback or onConsoleMessage before calling next
		next();
	} else {
		next();
	}
}

```

**Comment by rowanmanning** [comment] 2016-01-27 09:46
Oh yeah, cool. Well it's similar but the person writing the code is responsible for _everything_, and can set their own timeouts etc :)

**Comment by GlynnPhillips** [comment] 2016-01-27 09:49
Ohh yeah this was doing that as well _I think_ but I just removed the section where I was handling the callback from the user and added that comment because I didn't feel my handling of that callback was very elegant

**Comment by qaDream77** [comment] 2016-01-27 20:16
My biggest concern is related to authentication, although i do use quite a bit of angular. I was wondering how this method/solution would work with CAS or LDAP authentication which has redirects?

Example.

www.mytestsite.com/myapp/login.html
i enter my username, password and any other parameters and post this page. This will redirect me to an intermediary page which generates a token and then to

www.mytestsite.com/myapp/index.html

at this point i want pa11t to scan
www.mytestsite.com/myapp/index.html
www.mytestsite.com/myapp/contact.html
etc
as an authenticated user, should still be using the same session, cookies, etc that were generated on a successful authentication.

My question is, ideally all of this would be handled by phantomjs, which i don't think should be a problem, right? Pa11y would then just execute on the current page?

Cheers.

**Comment by GlynnPhillips** [comment] 2016-02-09 11:52
We have now added this functionality and it has been released as part of 3.5.0 and you can see the changes [here](https://github.com/nature/pa11y/pull/130)

@qaDream77 I believe this should cover your user case and you can see an example we have put together in the commonly asked questions [here](https://github.com/nature/pa11y#how-can-pa11y-log-in-if-my-site-has-a-log-in-form)

Cheers

**Closed by GlynnPhillips** 2016-02-09 11:52 UTC
Labels: feature

**Comment by qaDream77** [comment] 2016-03-15 21:00
Thank you very much! I'm going back to this now :) I have modified the example above to suit my website, but how do i run it?

phantomjs login_test.js

This throws a reference error: can't find variable pa11y

**Comment by GlynnPhillips** [comment] 2016-03-16 13:00
Hi @qaDream77 you need to run `pa11y` with the `beforeScript` option set within your config.

If you are running pa11y via the command line here is an example of how that can be achieved within a config file.

**config.js file example**

```
{
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        page.evaluate(function() {
            var user = document.querySelector('#username');
            var password = document.querySelector('#password');
            var submit = document.querySelector('#submit');

            user.value = 'exampleUser';
            password.value = 'password1234';

            submit.click();

        }, function() {

            waitUntil(function() {
                return window.location.href === 'http://example.com/myaccount';
            }, 20, next);
        });
    }
}
```

**Command example**

```
pa11y --config ./path/to/config.js nature.com
```

**Comment by rowanmanning** [comment] 2016-03-16 15:12
@GlynnPhillips: your example JS file needs a `module.exports`, otherwise :ok_hand:

**Comment by GlynnPhillips** [comment] 2016-03-16 15:26
oops, silly copy and paste error. Thanks and good catch Rowan.

Now updated

**Comment by qaDream77** [comment] 2016-03-16 16:22
I'll play around with it and come back. This is the confusing bit which is that i still provide nature.com as a parameter, is that still used by pa11y or no?

return window.location.href === 'http://example.com/myaccount';
and
pa11y --config ./path/to/config.js nature.com

Logically i want it to go to the login page and authenticate then redirect to my desired page for a scan. My phantomJS to accomplish this is:
```

var page = require('webpage').create();
var url = "https://sample.ca/app/";

page.onConsoleMessage = function(msg, lineNum, sourceId) {
    console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
};

page.open(url, function (status) {
    page.onConsoleMessage = function(msg, lineNum, sourceId) {
        console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
    };
    page.evaluate(function() {
        document.getElementById("username").value = "user1";
        document.getElementById("password").value = "password";
        document.getElementById("login").submit();
        // page is redirecting.
    });

    setTimeout(function () {
        page.evaluate(function () {
            console.log('haha');
        });
        page.render("p1.png");


        var url = "https://sample.ca/app/client/page_one.html";

        page.open(url, function (status) {
            setTimeout(function () {
                page.evaluate(function () {
                    console.log('haha');
                });
                page.render("p2.png");
                phantom.exit();
            }, 5000);
        });
    }, 5000);
});
```

I'll come back after i try to modify your above example and let you know how it goes :)

Cheers

**Comment by GlynnPhillips** [comment] 2016-03-16 16:30
Sorry @qaDream77 maybe it would be clearer is my example referenced `example.com` all the time instead of `nature.com`. I will change the above now to make that clearer

Your example is still trying to do everything with `phantomjs` when there is no need. `pa11y` spins up an instance of `phantomjs` for you so there is no need for some of the above.

Also from your example I guess you are trying to use `pa11y` from within a node/JavaScript project and not from the command line. Can you confirm for me if this is correct or if you just want to run a command on the command line?

Then I can provide an example with comments on how to do this.

**Comment by qaDream77** [comment] 2016-03-16 16:39
I am trying to run pa11y from the command line, I was just wondering because of the two different URL's :)

And the reason i posted my phantomJS code is because if you notice i have screenshots being taken, just to confirm for my own sanity that i'm actually being authenticated and redirected to my desired page. I had modified your code to the following
```

module.exports = {
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        page.evaluate(function() {
            var user = document.querySelector('#username');
            var password = document.querySelector('#password');
            var login = document.querySelector('#login');

            user.value = 'user1';
            password.value = 'password';

            login.click();

        }, function() {

            waitUntil(function() {
                return window.location.href === 'https://sample.ca/app/client/page_one.html';
            }, 20, next);
        });
	page.render("page.png");
    }
}
```

and my command line was

pa11y --config config.js "https://sample.ca/app/client/page_one.html"

However, page.png which is generated shows me on the login page not having submitted my request yet.

**Comment by qaDream77** [comment] 2016-03-16 17:25
I accidentally deleted the wrong comment :( Sorry!

I am trying to run form command line :) I modified your above code to the following:
**config.js
**
---
```
module.exports = {
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        page.evaluate(function() {
            var user = document.querySelector('#username');
            var password = document.querySelector('#password');
            var submit = document.querySelector('#login');

            user.value = 'user1';
            password.value = 'abc';

            submit.submit();
        }, function() {
            waitUntil(function() {
                return window.location.href === 'http://example.com/app/';
            }, 20, next);
        });
    }
}
```
The commands to test different pages are:

pa11y --config ./path/to/config.js "http://example.com/app/page_1.html"
pa11y --config ./path/to/config.js "http://example.com/app/page_2.html"
pa11y --config ./path/to/config.js "http://example.com/app/page_3.html"
pa11y --config ./path/to/config.js "http://example.com/app/page_4.html"

This works for me! Thank you! One question is, where do i add a sanity check? I would like phantom to take a screenshot of the loaded page!

`page.render("page.png");`

**Comment by GlynnPhillips** [comment] 2016-03-16 17:27
So the problem is with your call to the `waitUntil` function.

You are returning whenever the url is equal to `https://sample.ca/app/client/page_one.html` and this is the same as the url that you are passing to `pa11y` on the command line. 

This check of the url is done to validate that the login action has completed. In your example pa11y will continue and run the tests straight away before it has had time to perform your login because the url is already equal to `https://sample.ca/app/client/page_one.html`.

If on login your site doesn't redirect to a different url then you will need to use something else to validate that the login has been completed, for instance a using an element in the page that might be different once logged in.

This could be checking for the existence of an element that is not on the page until the user is logged in. Without knowing your code it might look something like this.

```
waitUntil(function() {
    // Element that doesn't exist until logged in
    var exampleElement = document.querySelector('#exampleElement');
    // returns true when element exists
    return exampleElement.length > 0;
}, 20, next);
```

**Comment by qaDream77** [comment] 2016-03-16 18:44
Well i have two methods of authentication.

1) LDAP, standard username and password and the redirect goes straight to the desired page! This works fine with the example script you provided, thank you!.

LDAP Login -> page_one

2) CAS, This method of authentication goes from the login page to a redirect which generates a success token which then redirects back to my desired page. This is a blank page.

CAS Login -> security check -> page_one

I am looking at the report pally generates and it does not hit my desired page

My phantomJS code is simple (it works for both LDAP and CAS):
```

var page = require('webpage').create();

page.open("https://sample.ca/app/admin/calendar", function(status) {

  if (status === "success") {
    page.evaluate(function() {
        document.getElementById("username").value = "user1";
        document.getElementById("password").value = "abc";
        document.getElementById("submit").click();
    });
    window.setTimeout(function() {
       page.render("page.png");
       phantom.exit();
    }, 5000);
  }
});
```

How can I translate the above code into the config.js?

---

I tried the following:

**cas_config.js**
```

module.exports = {
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        page.evaluate(function() {
            var user = document.querySelector('#username');
            var password = document.querySelector('#password');
            var submit = document.querySelector('#submit');

            user.value = 'user1';
            password.value = 'abc';

            submit.submit();
        }, function() {
            waitUntil(function() {
                return window.location.href === 'https://sample.ca/app/admin/';
            }, 20, next);
        });
    }
}
```
Run with: `pa11y --config cas_config.js "https://sample.ca/app/admin/calendar"`

Please take a look at the two URL's, i mean really unsure what i am doing wrong.

---

To answer your previous question, i know i can look for a element on the screen but i would prefer to be able to take a screen shot, if this is not doable that is fine. I was just wondering if it was :)

With phantomjs, it would be `page.render("page.png");`

**Comment by qaDream77** [comment] 2016-03-16 19:46
Just one more question about config.json! The values for username and password, as well as the url. Is there any ways to pass those in as command line arguments?

Want to write a shell script to go through a list of websites and perform a scan on them!

**Comment by GlynnPhillips** [comment] 2016-03-16 21:10
Ok, so I was answering your previous questions which you accidentally deleted where you mentioned that if was taking the screen shot and running pa11y before the login had completed which is why I suggested checking for an element instead of url as it seemed like your url didn't change.

Anyway you have something working now so onto your next question about taking a screen shot. You would want to do this right before `waitOver()` is called, like the below.

```
var waitUntil = function(condition, retries, waitOver) {
   page.evaluate(condition, function(error, result) {
       if (result || retries < 1) {
             page.render('page.png');
             waitOver();
        } else {
            retries -= 1;
            setTimeout(function() {
                waitUntil(condition, retries, waitOver);
            }, 200);
        }
    });
};
```

As far as I am aware there is no way to pass in the credentials as an argument or environment variable. This would be handled by separate config files or logic in your config file to determine which credentials to use.

**Comment by JordanGS** [comment] 2016-03-16 22:18
@GlynnPhillips 

I am so glad that you guys have implemented this! I have been tracking this project for a while now and and super excited that i am able to authenticate into my website! **Thank you** very much!

Sorry if i am interrupting on this discussion but i wanted to say that I like the idea of using screenshots, it allows for validation when integrating in Jenkins, so you can manually confirm that it authenticated!

I would like to ask one thing though, how would you analyze the following:

Say you have `page_one.html` and `page_two.html` but you cannot get to two unless page one was submitted with valid form data. I understand this is a bit more complicated and i understand how to do this in `phantomjs`, a little unsure though how to do multiple redirects in the `config.js` script. Also confused what my `two URL's` would be in this instance because if you try to go to `page_two.html` before `page_one.html` is validated, then you get an `error_page.html`.

Sorry for my English, please let me know if my question is unclear!

@qaDream77 Create a python script or shell script and generate a temporary file called `temp.js` with command line arguments injected in, keep your urls in an array and just iterate. Make sure to pipe the output to a unique out file each time. That's the easiest thing i can think of.

**Comment by GlynnPhillips** [comment] 2016-03-17 09:21
Hi @JordanGS no worries, if I am understanding your problem correctly it should be pretty straight forward to achieve using the login example in the [FAQ's](https://github.com/nature/pa11y#how-can-pa11y-log-in-if-my-site-has-a-log-in-form).

When running pa11y from the command line you would pass it the first url which contains the form that needs to be submitted with valid data.

`pa11y --config ~/path/to/config.js http://example.com/page_one.html`

Then your config file would look something like this

```
module.exports = {
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        page.evaluate(function() {
            // Code to populate and submit your form with valid data
        }, function() {
            waitUntil(function() {
                return window.location.href === 'http://example.com/page_two.html';
            }, 50, next);
        });
    }
}
```
The `waitUntil` function here is checking that the window has redirected to the second url. When this is equal to `true` the `beforeScript` is complete and will make its callback to pa11y allowing the pa11y tests to be run.

I hope that makes sense.

**Comment by qaDream77** [comment] 2016-04-26 20:28
@GlynnPhillips Hi Glenn, I went back to this and the login script doesn't work any more. I am unsure as to why.

**config.js
**
`module.exports = {
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };
        page.render("page.png");
        page.evaluate(function() {
            var user = document.querySelector('#username');
            var password = document.querySelector('#password');
            var submit = document.querySelector('#submit');

            user.value = 'userA';
            password.value = 'pwdB';

            submit.click();
        }, function() {
            waitUntil(function() {
                return window.location.href === 'https://website.ca/app/admin/calendar';
            }, 20, next);
        });
    }
}`

**Run command:** pa11y --config cas_config.js "https://website.ca/app/admin"

I tried

`submit.click();`
`submit.submit();`

is there any way to debug what's going on?

I also have a phantomjs script that i wrote which works fine and has no issues. It's just pa11y doesn't work any more.

pa11y version is 3.6.0 running on Ubuntu.
